// Login Page
export const APP_INIT = "APP_INIT";


// Login Page
export const HTTP_FORMTEXT_FETCHING = "HTTP_FORMTEXT_FETCHING";
export const HTTP_FORMTEXT_SUCCESS = "HTTP_FORMTEXT_SUCCESS";
export const HTTP_FORMTEXT_FAILED = "HTTP_FORMTEXT_FAILED";

// Register Page
export const HTTP_SING_FETCHING = "HTTP_SING_FETCHING";
export const HTTP_SING_SUCCESS = "HTTP_SING_SUCCESS";
export const HTTP_SING_FAILED = "HTTP_SING_FAILED";

export const HTTP_SIDE_FETCHING = "HTTP_SIDE_FETCHING";
export const HTTP_SIDE_SUCCESS = "HTTP_SIDE_SUCCESS";
export const HTTP_SIDE_FAILED = "HTTP_SIDE_FAILED";